version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: olesyachu/foodgram:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/build:/usr/share/nginx/html/
      # - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on: 
      - backend 
    restart: always

volumes:
  postgres_value:
  static_value:
  media_value:
  foodgram_frontend:
  