# Generated by Django 4.1.5 on 2023-02-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_favoriteshop_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='sum',
            new_name='amount',
        ),
    ]
