# Generated by Django 4.1.5 on 2023-02-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_follow_no_self_follow_follow_no_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_follow',
        ),
    ]
