# Generated by Django 4.1.5 on 2023-02-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_follow_no_self_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
